### ISSUE TITLE
multiple "Set-Cookie" header

### ISSUE THREAD

**Issue by arypurnomoz** [JuliaWeb/HttpServer.jl#22]
How to make a response with multiple Set-Cookie header? Dictionary only allowed to use one key for one value.

**Comment by JockLawrie** [comment]
How about the following version of Stefan's suggestion?

For any header with multiple entries have:
```
    typealias Multiheader Dict{String, Any}
    res.headers[my_multiheader]::Multiheader
```
The type alias distinguishes headers that appear (potentially) multiple times with different values from headers that appear once with a Dict{String, Any} value.

For example, to set multiple cookies:
```res.headers["Set-Cookie"] = Multiheader([(cookie_name1, value1), (cookie_name2, value2)])```

To set a single cookie:
```res.headers["Set-Cookie"] = Multiheader([(cookie_name, value)])```
or
```res.headers["Set-Cookie"] = Multiheader()```
```res.headers["Set-Cookie"][cookie_name] = value```
or
```setcookie(res, cookie_name::String, value::Any)```

Then ``HttpServer.write()`` needs to be modified to explicitly write headers with type ```Multiheader```, then delete such headers from res.headers, then write the remaining res.headers as is currently done.

**Comment by wildart** [comment]
I submitted [MultiDict PR to DataStructures](https://github.com/JuliaLang/DataStructures.jl/pull/90). As soon as it'll be merged, we'll get multiple header support.

**Comment by JockLawrie** [comment]
Great.
Question: To modify a value you first must find it. With your Multidict implementation this means searching a vector (one way or another). Would it not be faster to find the desired value via a hash function?

**Comment by JockLawrie** [comment]
Somewhat off topic, @wildart you seem to be doing some great work on the Julia web stack. Perhaps I can help with documentation? [Here's](https://bitbucket.org/jocklawrie/skeleton-webapp.jl) what I have in mind at the moment (see docs/outline.md in particular).

**Comment by wildart** [comment]
MultiDict will handle duplicate headers, not header values. Regarding to the performance, how many duplicate headers you would expect? As for multiple cookies inside a particular header value, it is up to the developer how to deal with that value.

**Comment by JockLawrie** [comment]
Re documentation, agreed, most of the interesting stuff happens in the middleware. Note that the purpose of [that repo](https://bitbucket.org/jocklawrie/skeleton-webapp.jl/overview) is to enable users to start building web apps. As such it explains how all the parts fit together, starting with server only, then adding templates, middleware, etc. The examples reflect this approach - they are a sequence of applications, each one adding a new feature into the mix. The outline indicates 7 examples, and I have only implemented 4...the other 3 are still to come and I'm sure there will be more after that.

I took the approach of a sequence of examples because it highlights what each part is for, and what it can and can't do. I've found that tutorials for other web stacks/frameworks also add features to an example application in a sequential manner, but maintain only one application rather than the full sequence of applications. By the time I'd added all the features to the application I was forgetting which part did what, and often had features that I didn't need (and was too confused to trim it down to essentials). I hope the sequence of applications provided helps the concepts stick better in the first place and makes it easier to back track when confused.

**Comment by JockLawrie** [comment]
The ```Multiheader``` that I proposed is similar to your Multidict, but has a Dict{String, Any} instead of a vector as the value. I agree that performance is unlikely to be an issue, so it seems the distinction is one of taste. Am I missing anything?

**Comment by JockLawrie** [comment]
Looks like this is ready to go. Is this correct or is there required MultiDict functionality not yet implemented?

If so then HttpCommon.jl requires the following changes (near as I can tell only Requests.jl uses cookies):

```
import DataStructures: MultiDict

...

type Response
    status::Int
    headers::Headers
    cookies::MultiDict{UTF8String, Cookie}
    data::Vector{UInt8}
    finished::Bool
    requests::Vector{Request}
end

...

Response(s::Int, h::Headers, d::HttpData) = Response(s, h, MultiDict{UTF8String, Cookie}(), d, false, Request[])
```

**Comment by JockLawrie** [comment]
Ugh, my bad.
It's ``Headers`` that needs changing, which involves more work.
Apologies. Ignore my last post.

**Comment by malmaud** [comment]
https://github.com/JuliaWeb/HttpServer.jl/pull/68 addresses this by definding a new `setcookie!(::Request, name, value, attrs)` method. I'm open for comments before merging it in a day or two.

**Comment by JockLawrie** [comment]
Nice. Great that dependence on DataStructures.jl is not required.
