### ISSUE TITLE
test and example hang -- no apparent response to url request

### ISSUE THREAD

**Issue by catawbasam** [JuliaWeb/HttpServer.jl#47]
On 64-bit red hat linux with newly updated packages, 
julia> VERSION
v"0.4.0-dev+3163"

The tests hang up at the line shown here:
```
julia> include("test/runtests.jl")
HttpServer utility functions
     - HttpServer.write does sensible things
5 facts verified.
HttpServer run
     - HttpServer can run the example
```

Also
```
julia> include("examples/hello.jl")
Listening on 8000...
```
does not respond to `http://localhost:8000/hello/name`

**Comment by catawbasam** [comment]
Turns out GnuTLS didn't build correctly. Closing.

**Comment by cwells** [comment]
I'm having the same issue (Fedora 21). Unfortunately, this issue was closed describing the problem, but not the solution.

Symptoms: anything using HttpServer hangs (or segfaults, depending on version of Julia). Apparent cause seems related to:

$ julia GnuTLS/test/runtests.jl 
julia: symbol lookup error: /lib64/libhogweed.so.2: undefined symbol: __gmpn_cnd_add_n

Any suggestions @catawbasam for how you resolved this?

**Comment by catawbasam** [comment]
Hi Cliff,

Sorry, I did not resolve it -- just concluded that the issue lay with
GnuTLS rather than HttpServer.jl.

regards,
Keith
